### ISSUE TITLE
[T122] - Mixed color channel on color2 setting

### ISSUE THREAD

**Issue by avDuma** [JeffHoogland/moksha#6]
Hi, another bug that I've seen on E17 and it won't be fixed.
https://phab.enlightenment.org/T122

I report here the description:
If I set a text object on edje with outlined effect, like OUTLINE_SHADOW and I link to a color_class editable by Settings -> Look -> Colors , I have a strange behaviour when I'm changing the color by Settings -> Look -> Colors.

example:

On a theme with a part like this:

    part { name: "my_text"; type: TEXT;
           effect: OUTLINE
           description { state: "default" 0.0;
             color_class: "border_title";
             color: 255 255 255 255;
             color2: 255 255 255 255;
             color3: 255 255 255 255;
             text { blah blah }
             }
         }

When I set as color2 of border title, on Settings -> Look -> Color , the Blue and the Green value are inverted.
Eg: I set color2 as 0 255 0 255 (the green) and I see 0 0 255 255 (the blue) and if I set 0 0 255 255 (the blu), I see 0 255 0 255 (the green).

The same things happens with yellow and fucsia:
If I set 255 0 255 255 (the fucsia) I'll see 255 255 0 255 (the yellow) and If I set 255 255 0 255 (the yellow) I'll see 255 0 255 255 (the fucsia)

Hope I am clear. The issue is visible only if I edit color2 and color3 by Settings -> Look -> Color Dialog, not if I set the color with the code.

**Comment by drammelt** [comment]
This is not a simple fix as far as I can see. I checked the rgb code and it all looks fine.
I cannot reproduce the bug, but I use the default theme.

The code that does fix this in master git uses a new API which cannot be backported simply.

**Comment by avDuma** [comment]
It seems to affect only color2, that I don't know where I can test on default theme.
By the way maybe on moksha it is already fixed with backporting feature. I am using E17.6 from Bodhi because I've understood it is the same.

**Comment by JeffHoogland** [comment]
avDuma - did you ever get around to seeing if this issue still exists in Moksha?

**Comment by SmartDuck** [comment]
It still exists in Moksha in the current 4.1.
what i think is going on, the index of the array input box is set to +1 this is why the value entered is displayed in the input box below.
